### ISSUE TITLE
Suggest Display Port out instead of HDMI

### ISSUE THREAD

**Issue by jcdutton** [TheGuyDanish/CM4_MATX#68]
Hi,

I suggest using Display Port out instead of HDMI.
Display Port out is much more flexible because it adds a power supply to the output.
One can then get adapters that convert it to all sorts of different outputs: DVI, HDMI, VGA etc.

**Comment by TheGuyDanish** [comment]
This is technically possible, but unfeasible. We do not decide what ports we can get out of the CM4. It depends entirely on the pins on the CM4 module. We could put an adapter IC in place that could turn the HDMI signal into DisplayPort, but at that point, you lose all the advantages and benefits, since in the end, it's still HDMI.
